import Head from 'next/head'


export default function AboutTheCompany() {
  return (
    <>
      <Head>
        <title>about_the_company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="aboutTheCompany">
            <div className="aboutTheCompany__wrapper">
                <h1 className="aboutTheCompany__title">О КОМПАНИИ</h1>
                
                <p className="aboutTheCompany__text">Компания <b>Индивидуальный предприниматель Романский Валерий Алексеевич</b>, ИНН <b>911007116568</b>, ОГРН <b>317910200031680</b> присвоен <b>16 марта 2017 г.</b></p>
                <ul className="aboutTheCompany__list">
                    <li className="aboutTheCompany__item">С 2003 года монтируем ПВХ и ТПО мембраны.</li>
                    <li className="aboutTheCompany__item">Сертифицированы как монтажники у трех ведущих производителей мембран.</li>
                    <li className="aboutTheCompany__item">Материалы напрямую от представителей заводов в Крыму.</li>
                    <li className="aboutTheCompany__item">Проводим гидроизоляцию объектов и сооружений самого разного уровня сложности и объемов.</li>
                    <li className="aboutTheCompany__item">Монтаж ПВХ или ТПО мембран производим в соответствии с международными стандартами, с применением современных технологий и оборудования.</li>
                    <li className="aboutTheCompany__item">Собственное оборудование исключает задержки и простои в выполнении монтажа мембраны.</li>
                    <li className="aboutTheCompany__item">Знаем и уважаем свое дело. Стремимся работать качественно, быстро и эффективно.</li>
                    <li className="aboutTheCompany__item">Практикуем индивидуальный подход к каждому проекту, помогая с выбором типа кровли, материалов, способа монтажа, выдаем рекомендаций по совершенствованию кровли.</li>
                    <li className="aboutTheCompany__item">Сосредоточены на монтаже ПВХ и ТПО мембран, в котором являемся специалистами.</li>
                    <li className="aboutTheCompany__item">Узкая специализация в сочетании с умением и опытом позволяет нам достойно выполнять работу и не беспокоиться за результаты своего труда.</li>
                    <li className="aboutTheCompany__item">Предоставляем гарантию на выполненные работы 5 лет.</li>
                </ul>
                <p className="aboutTheCompany__preface">Уважаемые будущие клиенты - заказчики, буду рад сотрудничать с Вами и предоставить весь спектр услуг по гидроизоляции с применением ПВХ  мембран, ТПО мембран, лайнера для бассейнов . Уверены, что уровень оказываемых  услуг позволит рассчитывать на долгосрочное сотрудничество.</p>
                <p className="aboutTheCompany__text"><b>Контактное лицо:</b></p>
                <p className="aboutTheCompany__text">Сухоцкий Глеб Владимирович</p>
                <p className="aboutTheCompany__text"><b>Email:</b> pvc-master@mail.ru</p>
                <p className="aboutTheCompany__text"><b>Моб.тел:</b>+7(978)016-78-23</p>
            </div>
        </div>

    </>
  )
}