import Head from 'next/head';
import { YMaps, Map, Placemark, RulerControl, TypeSelector, ZoomControl } from "@pbe/react-yandex-maps";

export default function Contacts() {

  const defaultState = {
    center: [44.948227, 34.100264], 
    zoom: 8
  };

  const copyMessege = () => {
    const contactsClipboard = document.querySelector('.contacts__clipboard');
    contactsClipboard.classList.add('contacts__clipboard--active');
    const interval = setTimeout(()=>{
      contactsClipboard.classList.remove('contacts__clipboard--active');
      clearInterval(interval);
    }, 3000)
  }

  const copyEmail = () => {
    navigator.clipboard.writeText(id_contacts_email.textContent);
    copyMessege();
  }

  const copyTel = () => {
    navigator.clipboard.writeText(id_contacts_tel.textContent);
    copyMessege();
  }

  return (
    <>
      <Head>
        <title>about_the_company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="contacts">
        <div className="contacts__wrapper">

          <div className='contacts__clipboard'>
            <p className='contacts__clipboard-title'>Текст скопирован</p>
          </div>

          <h1 className="contacts__title">КОНТАКТЫ</h1>
          <div className="contacts__inner">
            <div className="contacts__elements">
              <div className="contacts__element">
                <div className="contacts__element-title">Адрес:</div>
                <div className="contacts__element-desc">Крым, г.Симферополь</div>  
              </div>

              <div className="contacts__element">
                <div className="contacts__element-title">Телефон, Viber, Whatsapp:</div>
                <div className="contacts__element-tel" id='id_contacts_tel' onClick={copyTel}>+7(978)809-98-82</div>  
              </div>

              <div className="contacts__element">
                <div className="contacts__element-title">E-mail:</div>
                <a className="contacts__element-email" id='id_contacts_email' href='mailto:crimearoof@gmail.com'>crimearoof@gmail.com</a>  
              </div>

              <div className="contacts__element">
                <div className="contacts__element-title">Режим работы:</div>
                <div className="contacts__element-desc">пн–сб: 08:00–19:00 вс: выходной</div>  
              </div>
            </div>

            <div className="contacts__map">
              <YMaps>
                <Map  height={'90%'} width={'100%'}  defaultState={defaultState}>
                  <RulerControl/>
                  <TypeSelector/>
                  <ZoomControl/>
                  <Placemark geometry={[44.917973, 34.072084]}/>
                </Map>
              </YMaps>
            </div>
          </div>
        </div>   
    </div>
    </>
  )
}