import Head from 'next/head';
import servicesData from './Services.json';
import Image from 'next/image';

export default function Services() {



  return (
    <>
      <Head>
        <title>about_the_company</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="services">
            <div className="services__wrapper">
                <h1 className="services__title">УСЛУГИ</h1>
                {
                    servicesData.map(data => {
                        return (
                            <div className="services__item" key={data.id} data-scroll>
                                <h2 className="services__item-title">{data.title}</h2>
                                <Image className="services__item-img" src={data.img} alt="membrane" width={500} height={450} ></Image>
                                <div className="services__item-desc">Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
                                Maxime, voluptatem sunt, reiciendis quas, minus expedita labore eum culpa perferendis 
                                dignissimos tempore inventore ipsam totam. Culpa, eligendi? Reiciendis iste accusantium 
                                necessitatibus quibusdam deserunt. Qui eum ab odit sed nam fugit laborum sint labore 
                                deserunt temporibus dolores, officia est expedita ducimus magnam?</div>
                                <div className="services__item-line"></div>
                            </div>
                        )
                    })
                }
            </div>
        </div>
    </>
  )
}